import { defineConfig } from 'eslint/config'
import tseslint from '@electron-toolkit/eslint-config-ts'
import eslintConfigPrettier from '@electron-toolkit/eslint-config-prettier'
import eslintPluginReact from 'eslint-plugin-react'
import eslintPluginReactHooks from 'eslint-plugin-react-hooks'
import eslintPluginReactRefresh from 'eslint-plugin-react-refresh'

export default defineConfig(
  // `resources/**` holds vendored binaries (yt-dlp/ffmpeg and yt-dlp's bundled
  // python/JS, incl. minified solver files) — never lint those.
  // `CHANGELOG.md` is generated by release-please — never lint or format it.
  // `.specs/**` is authored prose (specs, plans, designs) — never lint or format it.
  {
    ignores: [
      '**/node_modules',
      '**/dist',
      '**/out',
      'scripts/**',
      'resources/**',
      'CHANGELOG.md',
      '.specs/**',
      // Native addons' Swift build output (SwiftPM `.build`) — generated artifacts.
      'native/**/.build/**',
      // Native addons' plain-JS files — the CommonJS entrypoints (thin hand-written
      // loaders that `require()` the compiled `.node` binary) and the ESM build scripts
      // (`scripts/build.mjs`) — can't carry TS return types, so the TS rules don't apply.
      // (Their `.d.ts` files still lint.)
      'native/**/*.{js,mjs,cjs}'
    ]
  },
  tseslint.configs.recommended,
  eslintPluginReact.configs.flat.recommended,
  eslintPluginReact.configs.flat['jsx-runtime'],
  {
    settings: {
      react: {
        version: 'detect'
      }
    }
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': eslintPluginReactHooks,
      'react-refresh': eslintPluginReactRefresh
    },
    rules: {
      ...eslintPluginReactHooks.configs.recommended.rules,
      ...eslintPluginReactRefresh.configs.vite.rules
    }
  },
  eslintConfigPrettier
)
